<?php

namespace AppBundle\Repository;

/**
 * CoordinatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesRepository extends \Doctrine\ORM\EntityRepository
{
}
