<?php

namespace AppBundle\Repository;

/**
 * DarkModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DarkModeRepository extends \Doctrine\ORM\EntityRepository
{
}
