<?php

namespace AppBundle\Repository;

/**
 * ElementListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementListeRepository extends \Doctrine\ORM\EntityRepository
{
}
